export const SET_DETAILS_SUCCESS = "SET_DETAILS_SUCCESS";
export const SET_COMPRESSION_SUCCESS = "SET_COMPRESSION_SUCCESS";
export const GET_UPDATE_SUCCESS = "GET_UPDATE_SUCCESS";
export const CLEAR_HISTORY = "CLEAR_HISTORY";

export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";
export const UPLOAD_REQUEST = "UPLOAD_REQUEST";
